name:                ip
version:             0.1.0.0
license:             BSD3
author:              "initprism"
maintainer:          "initprism@gmail.com"
copyright:           "2021 initprism"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- split
- optparse-applicative
- exceptions
- hedgehog

library:
  source-dirs: src

executables:
  ip-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ip

tests:
  ip-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ip
    - tasty
    - tasty-hspec
    - tasty-hedgehog
    - tasty-golden
    - filepath